##### step 1. load the iris.csv dataset.

##### 1. Write a Pandas program to get the data types of the given csv data (iris.csv ) fields

In [2]:
### code here
import pandas as pd
import numpy as np
data=pd.read_csv("D:\\Innomatics\\Pandas_assignment\\Pandas_day_1\\Iris.csv")
data.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In These Data Set their are three data types float is 4, int is 1 and object 1

##### 2. Write a Pandas program to find the sum, mean, max, min value of 'SepalLengthCm' column of dataframe

In [19]:
### code here
a=data["SepalLengthCm"].sum()
b=data["SepalLengthCm"].mean()
c=data["SepalLengthCm"].max()
d=data["SepalLengthCm"].min()

print("sum:")
print(a)
print("mean:")
print(b)
print("max:")
print(c)
print("min:")
print(d)

sum:
876.5
mean:
5.843333333333335
max:
7.9
min:
4.3

##### 3. Write a Pandas program to import iris data and skipping first twenty rows into a Pandas dataframe.

In [33]:
### code here
data=pd.read_csv("D:\\Innomatics\\Pandas_assignment\\Pandas_day_1\\Iris.csv",skiprows=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,21,5.4,3.4,1.7,0.2,Iris-setosa
1,22,5.1,3.7,1.5,0.4,Iris-setosa
2,23,4.6,3.6,1.0,0.2,Iris-setosa
3,24,5.1,3.3,1.7,0.5,Iris-setosa
4,25,4.8,3.4,1.9,0.2,Iris-setosa
...,...,...,...,...,...,...
125,146,6.7,3.0,5.2,2.3,Iris-virginica
126,147,6.3,2.5,5.0,1.9,Iris-virginica
127,148,6.5,3.0,5.2,2.0,Iris-virginica
128,149,6.2,3.4,5.4,2.3,Iris-virginica
129,150,5.9,3.0,5.1,1.8,Iris-virginica

##### 4. Write a Pandas program to display the last ten rows.

In [35]:
### code here
data.tail(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
120,141,6.7,3.1,5.6,2.4,Iris-virginica
121,142,6.9,3.1,5.1,2.3,Iris-virginica
122,143,5.8,2.7,5.1,1.9,Iris-virginica
123,144,6.8,3.2,5.9,2.3,Iris-virginica
124,145,6.7,3.3,5.7,2.5,Iris-virginica
125,146,6.7,3.0,5.2,2.3,Iris-virginica
126,147,6.3,2.5,5.0,1.9,Iris-virginica
127,148,6.5,3.0,5.2,2.0,Iris-virginica
128,149,6.2,3.4,5.4,2.3,Iris-virginica
129,150,5.9,3.0,5.1,1.8,Iris-virginica

##### 5. Write a Pandas program to create a subtotal of "PetalLengthCm" against Species from the dataframe.

In [31]:
### code here
data['PetalLengthCm'].sum()

563.8

###### 6. Write a Pandas program to find details where "PetalLengthCm" > 2.

In [32]:
### code here
data.loc[data['PetalLengthCm']>2]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

###### 7. Write a Pandas program find all records that include two specific Species.

In [1]:
### code here
import pandas as pd
data=pd.read_csv(r"D:\innomatics\Iris.csv")
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
data.loc[data['Species']=='Iris-setosa']

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa

In [4]:
data.loc[data['Species']=='Iris-virginica']

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
100,101,6.3,3.3,6.0,2.5,Iris-virginica
101,102,5.8,2.7,5.1,1.9,Iris-virginica
102,103,7.1,3.0,5.9,2.1,Iris-virginica
103,104,6.3,2.9,5.6,1.8,Iris-virginica
104,105,6.5,3.0,5.8,2.2,Iris-virginica
105,106,7.6,3.0,6.6,2.1,Iris-virginica
106,107,4.9,2.5,4.5,1.7,Iris-virginica
107,108,7.3,2.9,6.3,1.8,Iris-virginica
108,109,6.7,2.5,5.8,1.8,Iris-virginica
109,110,7.2,3.6,6.1,2.5,Iris-virginica
110,111,6.5,3.2,5.1,2.0,Iris-virginica
111,112,6.4,2.7,5.3,1.9,Iris-virginica
112,113,6.8,3.0,5.5,2.1,Iris-virginica
113,114,5.7,2.5,5.0,2.0,Iris-virginica
114,115,5.8,2.8,5.1,2.4,Iris-virginica
115,116,6.4,3.2,5.3,2.3,Iris-virginica
116,117,6.5,3.0,5.5,1.8,Iris-virginica
117,118,7.7,3.8,6.7,2.2,Iris-virginica
118,119,7.7,2.6,6.9,2.3,Iris-virginica
119,120,6.0,2.2,5.0,1.5,Iris-virginica
120,121,6.9,3.2,5.7,2.3,Iris-virginica
121,122,5.6,2.8,4.9,2.0,Iris-virginica
122,123,7.7,2.8,6.7,2.0,Iris-virginica
123,124,6.3,2.7,4.9,1.8,Iris-virginica
124,125,6.7,3.3,5.7,2.1,Iris-virginica
125,126,7.2,3.2,6.0,1.8,Iris-virginica
126,127,6.2,2.8,4.8,1.8,Iris-virginica
127,128,6.1,3.0,4.9,1.8,Iris-virginica
128,129,6.4,2.8,5.6,2.1,Iris-virginica
129,130,7.2,3.0,5.8,1.6,Iris-virginica
130,131,7.4,2.8,6.1,1.9,Iris-virginica
131,132,7.9,3.8,6.4,2.0,Iris-virginica
132,133,6.4,2.8,5.6,2.2,Iris-virginica
133,134,6.3,2.8,5.1,1.5,Iris-virginica
134,135,6.1,2.6,5.6,1.4,Iris-virginica
135,136,7.7,3.0,6.1,2.3,Iris-virginica
136,137,6.3,3.4,5.6,2.4,Iris-virginica
137,138,6.4,3.1,5.5,1.8,Iris-virginica
138,139,6.0,3.0,4.8,1.8,Iris-virginica
139,140,6.9,3.1,5.4,2.1,Iris-virginica
140,141,6.7,3.1,5.6,2.4,Iris-virginica
141,142,6.9,3.1,5.1,2.3,Iris-virginica
142,143,5.8,2.7,5.1,1.9,Iris-virginica
143,144,6.8,3.2,5.9,2.3,Iris-virginica
144,145,6.7,3.3,5.7,2.5,Iris-virginica
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

###### 8.  Write a Pandas program to sort the records by the SepalLengthCm column.

In [36]:
### code here
data.sort_values(by=['SepalLengthCm'])

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
22,43,4.4,3.2,1.3,0.2,Iris-setosa
18,39,4.4,3.0,1.3,0.2,Iris-setosa
21,42,4.5,2.3,1.3,0.3,Iris-setosa
2,23,4.6,3.6,1.0,0.2,Iris-setosa
27,48,4.6,3.2,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
115,136,7.7,3.0,6.1,2.3,Iris-virginica
102,123,7.7,2.8,6.7,2.0,Iris-virginica
98,119,7.7,2.6,6.9,2.3,Iris-virginica
97,118,7.7,3.8,6.7,2.2,Iris-virginica
111,132,7.9,3.8,6.4,2.0,Iris-virginica

##### 9. Write a Pandas program to insert a column in the sixth position of dataframe and fill it with NaN values.

In [37]:
### code here

data.insert(5,"NaNValues",np.nan)
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,NaNValues,Species
0,21,5.4,3.4,1.7,0.2,NaN,Iris-setosa
1,22,5.1,3.7,1.5,0.4,NaN,Iris-setosa
2,23,4.6,3.6,1.0,0.2,NaN,Iris-setosa
3,24,5.1,3.3,1.7,0.5,NaN,Iris-setosa
4,25,4.8,3.4,1.9,0.2,NaN,Iris-setosa
...,...,...,...,...,...,...,...
125,146,6.7,3.0,5.2,2.3,NaN,Iris-virginica
126,147,6.3,2.5,5.0,1.9,NaN,Iris-virginica
127,148,6.5,3.0,5.2,2.0,NaN,Iris-virginica
128,149,6.2,3.4,5.4,2.3,NaN,Iris-virginica
129,150,5.9,3.0,5.1,1.8,NaN,Iris-virginica

##### 10. Write a Pandas program to add summation to a row of the dataframe.

In [2]:
### code here
sum_row=data[["SepalLengthCm", "SepalWidthCm"]].sum()
data_sum=pd.DataFrame(data=sum_row).T
data_sum=data_sum.reindex(columns=data.columns)
data_sum

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0 NaN          876.5         458.1            NaN           NaN      NaN

In [10]:
#one more technic for add summation

data=pd.read_csv(r"D:\innomatics\Iris.csv")
a=data['SepalLengthCm'].sum()
b=data['SepalWidthCm'].sum()
c=data['PetalLengthCm'].sum()
d=data['PetalWidthCm'].sum()

In [11]:
data=data.append({'SepalLengthCm':a,'SepalWidthCm':b,'PetalLengthCm':c,'PetalWidthCm':d},ignore_index=True)

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_16720\4119545005.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data=data.append({'SepalLengthCm':a,'SepalWidthCm':b,'PetalLengthCm':c,'PetalWidthCm':d},ignore_index=True)

In [12]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1.0,5.1,3.5,1.4,0.2,Iris-setosa
1,2.0,4.9,3.0,1.4,0.2,Iris-setosa
2,3.0,4.7,3.2,1.3,0.2,Iris-setosa
3,4.0,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
146,147.0,6.3,2.5,5.0,1.9,Iris-virginica
147,148.0,6.5,3.0,5.2,2.0,Iris-virginica
148,149.0,6.2,3.4,5.4,2.3,Iris-virginica
149,150.0,5.9,3.0,5.1,1.8,Iris-virginica
150,NaN,876.5,458.1,563.8,179.8,NaN